# EXPERIMENT 6 – DATA VISUALIZATION USING POWER BI

## Aim
To import, transform, analyze, and visualize data using Power BI Desktop and create interactive dashboards and reports for decision-making.

## Software Requirements
- Microsoft Power BI Desktop
- Microsoft Excel
- CSV Dataset

## Theory
Power BI is a Business Intelligence (BI) tool developed by Microsoft that enables users to import data, transform data, build dashboards, and perform business analytics. Power BI converts raw data into meaningful insights through interactive visualizations.

## Dataset
This experiment uses the supplied IPL ball-by-ball dataset.

## Learning Outcome
The IPL dataset can be transformed into an interactive dashboard containing KPI cards, charts, and slicers for season and team-wise analysis.

In [1]:
import pandas as pd
import numpy as np

ipl = pd.read_csv("IPL_ball_by_ball_updated.csv")

print("Dataset loaded successfully.")
print("Rows:", len(ipl))
print("Columns:", len(ipl.columns))
print("Shape:", ipl.shape)
print("Seasons:", int(ipl["season"].min()), "to", int(ipl["season"].max()))
print("\nColumn names:")
print(list(ipl.columns))

Dataset loaded successfully.
Rows: 243815
Columns: 22
Shape: (243815, 22)
Seasons: 2008 to 2023

Column names:
['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed']

## Algorithm 1 – Import Data into Power BI

1. Open **Power BI Desktop**.
2. Select **Home → Get Data → Text/CSV**.
3. Select `IPL_ball_by_ball_updated.csv`.
4. Preview the data.
5. Click **Load**.

The same IPL CSV used in this notebook is supplied with the experiment.

In [2]:
print("First 10 rows of the IPL dataset:")
ipl.head(10)

First 10 rows of the IPL dataset:

   match_id  season  ... other_wicket_type other_player_dismissed
0    335982    2008  ...               NaN                    NaN
1    335982    2008  ...               NaN                    NaN
2    335982    2008  ...               NaN                    NaN
3    335982    2008  ...               NaN                    NaN
4    335982    2008  ...               NaN                    NaN
5    335982    2008  ...               NaN                    NaN
6    335982    2008  ...               NaN                    NaN
7    335982    2008  ...               NaN                    NaN
8    335982    2008  ...               NaN                    NaN
9    335982    2008  ...               NaN                    NaN

[10 rows x 22 columns]

## Algorithm 2 – Transform Data using Power Query

1. Select **Home → Transform Data**.
2. Check the data types of all columns.
3. Rename columns if required.
4. Check for null or blank values.
5. Remove unnecessary columns where appropriate.
6. Apply the transformations using **Close & Apply**.

In [3]:
print("Data types:")
print(ipl.dtypes.to_string())

print("\nMissing values:")
print(ipl.isnull().sum().to_string())

Data types:
match_id                    int64
season                      int64
start_date                 object
venue                      object
innings                     int64
ball                      float64
batting_team               object
bowling_team               object
striker                    object
non_striker                object
bowler                     object
runs_off_bat                int64
extras                      int64
wides                     float64
noballs                   float64
byes                      float64
legbyes                   float64
penalty                   float64
wicket_type                object
player_dismissed           object
other_wicket_type         float64
other_player_dismissed    float64

Missing values:
match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     236163
noballs                   242797
byes                      243187
legbyes                   240037
penalty                   243813
wicket_type               231748
player_dismissed          231748
other_wicket_type         243815
other_player_dismissed    243815

## Algorithm 3 – Create KPI Measures

Create the following DAX measures in Power BI:

```DAX
Total Runs = SUM(IPL_ball_by_ball_updated[runs_off_bat])

Total Matches = DISTINCTCOUNT(IPL_ball_by_ball_updated[match_id])

Total Deliveries = COUNTROWS(IPL_ball_by_ball_updated)

Runs Per Match = DIVIDE([Total Runs], [Total Matches])
```

These measures can be displayed using **Card** visuals.

In [4]:
total_runs = int(ipl["runs_off_bat"].sum())
total_matches = int(ipl["match_id"].nunique())
total_deliveries = int(len(ipl))
runs_per_match = round(total_runs / total_matches, 2)

print("KPI VALUES FROM THE SUPPLIED IPL DATA")
print("--------------------------------------")
print("Total Runs:", total_runs)
print("Total Matches:", total_matches)
print("Total Deliveries:", total_deliveries)
print("Runs Per Match:", runs_per_match)

KPI VALUES FROM THE SUPPLIED IPL DATA
--------------------------------------
Total Runs: 305406
Total Matches: 1024
Total Deliveries: 243815
Runs Per Match: 298.25

## Algorithm 4 – Line Chart: Total Runs by Season

In Power BI:
- Insert **Line Chart**
- X-axis → `season`
- Y-axis → `Total Runs`
- Add a suitable title

This visualization shows the trend of IPL runs across seasons.

In [5]:
season_summary = (
    ipl.groupby("season")
       .agg(
           Total_Runs=("runs_off_bat", "sum"),
           Matches=("match_id", "nunique")
       )
       .reset_index()
)

print("Season-wise total runs and matches:")
season_summary

Season-wise total runs and matches:

    season  Total_Runs  Matches
0     2008       16809       58
1     2009       15376       57
2     2010       17753       60
3     2011       19928       73
4     2012       21323       74
5     2013       21487       76
6     2014       17943       60
7     2015       17427       59
8     2016       17962       60
9     2017       17920       59
10    2018       19098       60
11    2019       18607       60
12    2020       18566       60
13    2021       17727       60
14    2022       23052       74
15    2023       24428       74

## Algorithm 5 – Bar Chart: Team-wise Total Runs

In Power BI:
- Insert **Clustered Bar Chart**
- Axis → `batting_team`
- Values → `Total Runs`
- Sort by Total Runs in descending order

This compares the run contribution of IPL teams.

In [6]:
team_summary = (
    ipl.groupby("batting_team")
       .agg(
           Total_Runs=("runs_off_bat", "sum"),
           Matches=("match_id", "nunique")
       )
       .reset_index()
       .sort_values("Total_Runs", ascending=False)
)

print("Team-wise total runs:")
team_summary

Team-wise total runs:

                   batting_team  Total_Runs  Matches
10               Mumbai Indians       37523      247
16  Royal Challengers Bangalore       35810      240
8         Kolkata Knight Riders       34668      237
0           Chennai Super Kings       34334      223
13             Rajasthan Royals       30541      205
6               Kings XI Punjab       28541      190
17          Sunrisers Hyderabad       24735      166
3              Delhi Daredevils       23022      161
2                Delhi Capitals       11764       77
1               Deccan Chargers       10885       75
12                 Punjab Kings        6670       42
11                Pune Warriors        6040       45
5                Gujarat Titans        5423       33
9          Lucknow Super Giants        4731       30
4                 Gujarat Lions        4629       30
14       Rising Pune Supergiant        2370       16
15      Rising Pune Supergiants        1962       14
7          Kochi Tuskers Kerala        1758       14

## Algorithm 6 – Pie/Donut Chart: Team Contribution

In Power BI:
- Insert **Donut Chart**
- Legend → `batting_team`
- Values → `Total Runs`

The chart shows the proportion of total IPL runs contributed by each team.

In [7]:
team_share = team_summary[["batting_team", "Total_Runs"]].copy()
team_share["Percentage"] = (
    team_share["Total_Runs"] / team_share["Total_Runs"].sum() * 100
).round(2)

print("Team contribution percentages:")
team_share

Team contribution percentages:

                   batting_team  Total_Runs  Percentage
10               Mumbai Indians       37523       12.29
16  Royal Challengers Bangalore       35810       11.73
8         Kolkata Knight Riders       34668       11.35
0           Chennai Super Kings       34334       11.24
13             Rajasthan Royals       30541       10.00
6               Kings XI Punjab       28541        9.35
17          Sunrisers Hyderabad       24735        8.10
3              Delhi Daredevils       23022        7.54
2                Delhi Capitals       11764        3.85
1               Deccan Chargers       10885        3.56
12                 Punjab Kings        6670        2.18
11                Pune Warriors        6040        1.98
5                Gujarat Titans        5423        1.78
9          Lucknow Super Giants        4731        1.55
4                 Gujarat Lions        4629        1.52
14       Rising Pune Supergiant        2370        0.78
15      Rising Pune Supergiants        1962        0.64
7          Kochi Tuskers Kerala        1758        0.58

## Algorithm 7 – Scatter Chart: Runs vs Deliveries

In Power BI:
- Insert **Scatter Chart**
- X-axis → number of deliveries
- Y-axis → total runs
- Details → `batting_team`

This can be used to study the relationship between team batting activity and runs.

In [8]:
scatter_summary = (
    ipl.groupby("batting_team")
       .agg(
           Total_Runs=("runs_off_bat", "sum"),
           Deliveries=("match_id", "size")
       )
       .reset_index()
)

print("Team-wise runs and deliveries:")
print(scatter_summary.to_string(index=False))
print("\nCorrelation between team deliveries and total runs:",
      round(scatter_summary["Deliveries"].corr(scatter_summary["Total_Runs"]), 4))

Team-wise runs and deliveries:
               batting_team  Total_Runs  Deliveries
        Chennai Super Kings       34334       26932
            Deccan Chargers       10885        9034
             Delhi Capitals       11764        9305
           Delhi Daredevils       23022       18786
              Gujarat Lions        4629        3566
             Gujarat Titans        5423        4020
            Kings XI Punjab       28541       22646
       Kochi Tuskers Kerala        1758        1582
      Kolkata Knight Riders       34668       27920
       Lucknow Super Giants        4731        3672
             Mumbai Indians       37523       29750
              Pune Warriors        6040        5443
               Punjab Kings        6670        5140
           Rajasthan Royals       30541       24410
     Rising Pune Supergiant        2370        1900
    Rising Pune Supergiants        1962        1580
Royal Challengers Bangalore       35810       28205
        Sunrisers Hyderabad       24735       19924

Correlation between team deliveries and total runs: 0.9997

## Algorithm 8 – Add Interactive Slicers

Add slicers in Power BI for:
- `season`
- `batting_team`
- `bowling_team`

Selecting a value in a slicer filters the dashboard visuals interactively.

In [9]:
print("Available seasons:")
print(sorted(ipl["season"].dropna().unique().tolist()))

print("\nNumber of batting teams:", ipl["batting_team"].nunique())
print("Number of bowling teams:", ipl["bowling_team"].nunique())

Available seasons:
[2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

Number of batting teams: 18
Number of bowling teams: 18

## Suggested Dashboard Layout

```text
+------------------------------------------------------+
|              IPL PERFORMANCE DASHBOARD               |
+-------------+---------------+------------------------+
| Total Runs  | Total Matches | Runs Per Match         |
+-------------+---------------+------------------------+
|        Total Runs by Season – Line Chart             |
+---------------------------+-------------------------+
| Team-wise Total Runs      | Team Contribution        |
| Bar Chart                 | Donut Chart              |
+---------------------------+-------------------------+
| Runs vs Deliveries – Scatter Chart                   |
+------------------------------------------------------+
| Season | Batting Team | Bowling Team – Slicers     |
+------------------------------------------------------+
```

## Applications
- Sports analytics
- Business intelligence
- Performance analysis
- Interactive reporting
- Decision-making

## Advantages
- Interactive dashboards
- Easy filtering and drill-down
- Clear visual representation
- Combines multiple data sources
- Supports analytical decision-making

## Precautions
1. Verify data types before creating visuals.
2. Use meaningful chart titles and labels.
3. Select suitable visualizations.
4. Check calculations and measures.
5. Avoid misleading scales.

## Result

The IPL dataset was successfully imported and analyzed for Power BI visualization. KPI measures, season-wise analysis, team-wise analysis, contribution analysis, scatter analysis, and interactive slicer requirements were prepared for an IPL Power BI dashboard.

**Note:** Power BI Desktop itself is required to render and save the final `.pbix` dashboard. The numerical outputs above are actual outputs calculated from the supplied IPL dataset.