# DATA VISUALIZATION TECHNIQUES LAB
## Experiment 7 – Data Visualization Using Tableau

**Dataset:** IPL Ball-by-Ball Dataset (2008–2023)

### Aim
To connect, prepare, analyze, and visualize IPL data using Tableau and create interactive visualizations, dashboards, and stories.

### Software Requirements
- Tableau Desktop
- CSV / Excel dataset
- IPL Ball-by-Ball Dataset
- Python 3.x and Jupyter Notebook for data preparation and verification

### Theory
Tableau is a data visualization and business intelligence tool used to connect to data sources, prepare data, create visualizations, and build interactive dashboards and stories.

This experiment covers data connection, preparation, bar charts, line charts, pie charts, tables and cross-tabs, formatting, filters, parameters, calculated fields, heatmaps, treemaps, bubble charts, dashboards, and stories.

## Learning Outcomes
- Connect an IPL dataset to Tableau.
- Prepare and inspect data.
- Create basic and advanced Tableau visualizations.
- Use filters, parameters, and calculated fields.
- Build an interactive dashboard and story.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("IPL_ball_by_ball_updated.csv")

print("IPL dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Seasons:", df["season"].min(), "to", df["season"].max())

IPL dataset loaded successfully.
Rows: 243815
Columns: 22
Seasons: 2008 to 2023

In [2]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 records:")
display(df.head())

Column names:
['match_id', 'season', 'start_date', 'venue', 'innings', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type', 'other_player_dismissed']

First 5 records:

   match_id  season  ... other_wicket_type other_player_dismissed
0    335982    2008  ...               NaN                    NaN
1    335982    2008  ...               NaN                    NaN
2    335982    2008  ...               NaN                    NaN
3    335982    2008  ...               NaN                    NaN
4    335982    2008  ...               NaN                    NaN

[5 rows x 22 columns]

In [3]:
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243815 entries, 0 to 243814
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243815 non-null  int64
 1   season                  243815 non-null  int64
 2   start_date              243815 non-null  object
 3   venue                   243815 non-null  object
 4   innings                 243815 non-null  int64
 5   ball                    243815 non-null  float64
 6   batting_team            243815 non-null  object
 7   bowling_team            243815 non-null  object
 8   striker                 243815 non-null  object
 9   non_striker             243815 non-null  object
 10  bowler                  243815 non-null  object
 11  runs_off_bat            243815 non-null  int64
 12  extras                  243815 non-null  int64
 13  wides                   7652 non-null    float64
 14  noballs                 1018 non-null    float64
 15  byes                    628 non-null     float64
 16  legbyes                 3778 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             12067 non-null   object
 19  player_dismissed        12067 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
dtypes: float64(8), int64(5), object(9)
memory usage: 40.9+ MB

In [4]:
print("Missing values:")
missing = df.isna().sum()
print(missing[missing > 0].sort_values(ascending=False))

Missing values:
other_wicket_type         243815
other_player_dismissed    243815
penalty                   243813
byes                      243187
noballs                   242797
legbyes                   240037
wides                     236163
player_dismissed          231748
wicket_type               231748
dtype: int64

## Algorithm 1 – Connecting Data to Tableau
1. Open Tableau Desktop.
2. Select **Connect → Text File**.
3. Select `IPL_ball_by_ball_updated.csv`.
4. Verify the fields and data types.
5. Move to **Sheet 1** to begin visualization.

In [5]:
required = ["season","match_id","batting_team","bowling_team","batter","bowler","runs_off_bat","total_runs"]
print("Tableau field verification:")
for col in required:
    print(f"{col}: {'Available' if col in df.columns else 'Missing'}")

Tableau field verification:
season: Available
match_id: Available
batting_team: Available
bowling_team: Available
batter: Missing
bowler: Available
runs_off_bat: Available
total_runs: Missing

## Algorithm 2 – Data Preparation in Tableau
1. Review field names and data types.
2. Rename fields if required.
3. Hide unnecessary fields.
4. Check null values and inconsistent categories.
5. Create calculated fields for derived metrics.
6. Use filters to restrict the analysis when required.

In [6]:
print("Duplicate rows:", df.duplicated().sum())
print("Unique matches:", df["match_id"].nunique())
print("Unique batting teams:", df["batting_team"].nunique())
print("Unique bowling teams:", df["bowling_team"].nunique())

Duplicate rows: 0
Unique matches: 1024

Unique batting teams: 18
Unique bowling teams: 18

## Algorithm 3 – Bar Chart
**Objective:** Compare total runs scored by batting team.

### Tableau steps
- Put `batting_team` on **Rows**.
- Put `runs_off_bat` on **Columns** and use **SUM**.
- Sort descending.
- Enable data labels.
- Add a meaningful title.

In [7]:
team_runs = df.groupby("batting_team")["runs_off_bat"].sum().sort_values(ascending=False)
print("Total runs by batting team:")
print(team_runs.to_string())

Total runs by batting team:
batting_team
Mumbai Indians                 37523
Royal Challengers Bangalore    35810
Kolkata Knight Riders          34668
Chennai Super Kings            34334
Rajasthan Royals               30541
Kings XI Punjab                28541
Sunrisers Hyderabad            24735
Delhi Daredevils               23022
Delhi Capitals                 11764
Deccan Chargers                10885
Punjab Kings                    6670
Pune Warriors                   6040
Gujarat Titans                  5423
Lucknow Super Giants            4731
Gujarat Lions                   4629
Rising Pune Supergiant          2370
Rising Pune Supergiants         1962
Kochi Tuskers Kerala            1758

## Algorithm 4 – Line Chart
**Objective:** Show IPL batting-run trend across seasons.

### Tableau steps
- Put `season` on **Columns**.
- Put `runs_off_bat` on **Rows** using **SUM**.
- Select the **Line** mark.
- Add labels/tooltips and a suitable title.

In [8]:
season_runs = df.groupby("season")["runs_off_bat"].sum().sort_index()
print("Total runs by season:")
print(season_runs.to_string())

Total runs by season:
season
2008    16809
2009    15376
2010    17753
2011    19928
2012    21323
2013    21487
2014    17943
2015    17427
2016    17962
2017    17920
2018    19098
2019    18607
2020    18566
2021    17727
2022    23052
2023    24428

## Algorithm 5 – Pie Chart
**Objective:** Show the share of total runs among the top batting teams.

### Tableau steps
- Put `batting_team` on **Color**.
- Put `SUM(runs_off_bat)` on **Angle**.
- Change Marks to **Pie**.
- Put team and run values on **Label**.
- Format labels as percentages where appropriate.

In [9]:
top6 = team_runs.head(6)
share = (top6 / top6.sum() * 100).round(2)
print("Top 6 teams by total batting runs:")
display(pd.DataFrame({"Total Runs": top6, "Share (%)": share}))

Top 6 teams by total batting runs:

                             Total Runs  Share (%)
batting_team
Mumbai Indians                    37523      18.63
Royal Challengers Bangalore       35810      17.78
Kolkata Knight Riders             34668      17.21
Chennai Super Kings               34334      17.05
Rajasthan Royals                  30541      15.16
Kings XI Punjab                   28541      14.17

## Algorithm 6 – Tables and Cross-Tabs
Create a season-versus-team cross-tab.

### Tableau steps
- `season` → **Rows**
- `batting_team` → **Columns**
- `runs_off_bat` → **Text**
- Aggregation → **SUM**

In [10]:
cross_tab = pd.pivot_table(df, index="season", columns="batting_team",
                             values="runs_off_bat", aggfunc="sum", fill_value=0)
print("Season × Batting Team cross-tab:")
display(cross_tab)

Season × Batting Team cross-tab:

batting_team  Chennai Super Kings  ...  Sunrisers Hyderabad
season                             ...
2008                         2365  ...                    0
2009                         2084  ...                    0
2010                         2442  ...                    0
2011                         2461  ...                    0
2012                         2717  ...                    0
2013                         2671  ...                 2197
2014                         2519  ...                 1943
2015                         2564  ...                 2117
2016                            0  ...                 2549
2017                            0  ...                 2262
2018                         2698  ...                 2600
2019                         2346  ...                 2353
2020                         2095  ...                 2397
2021                         2607  ...                 1965
2022                         2165  ...                 2084
2023                         2600  ...                 2268

[16 rows x 18 columns]

## Algorithm 7 – Heatmap
Create a heatmap from the season/team cross-tab.

### Tableau steps
- `season` → Rows
- `batting_team` → Columns
- `SUM(runs_off_bat)` → Color
- Change Marks to **Square**
- Increase square size and format the color legend.

In [11]:
print("Heatmap data prepared.")
print("Seasons:", cross_tab.shape[0])
print("Teams:", cross_tab.shape[1])
display(cross_tab.head())

Heatmap data prepared.
Seasons: 16
Teams: 18

batting_team  Chennai Super Kings  ...  Sunrisers Hyderabad
season                             ...
2008                         2365  ...                    0
2009                         2084  ...                    0
2010                         2442  ...                    0
2011                         2461  ...                    0
2012                         2717  ...                    0

[5 rows x 18 columns]

## Algorithm 8 – Treemap
**Objective:** Represent team contribution using rectangle size.

### Tableau steps
- Select `batting_team` and `runs_off_bat`.
- Choose **Show Me → Treemap**.
- Use `SUM(runs_off_bat)` for Size.
- Use `batting_team` for Color and Label.

In [12]:
treemap_data = team_runs.reset_index()
treemap_data.columns = ["batting_team", "total_runs"]
print("Treemap data:")
display(treemap_data)

Treemap data:

                   batting_team  total_runs
0                Mumbai Indians       37523
1   Royal Challengers Bangalore       35810
2         Kolkata Knight Riders       34668
3           Chennai Super Kings       34334
4              Rajasthan Royals       30541
5               Kings XI Punjab       28541
6           Sunrisers Hyderabad       24735
7              Delhi Daredevils       23022
8                Delhi Capitals       11764
9               Deccan Chargers       10885
10                 Punjab Kings        6670
11                Pune Warriors        6040
12               Gujarat Titans        5423
13         Lucknow Super Giants        4731
14                Gujarat Lions        4629
15       Rising Pune Supergiant        2370
16      Rising Pune Supergiants        1962
17         Kochi Tuskers Kerala        1758

## Algorithm 9 – Bubble Chart
**Objective:** Compare teams using bubble size.

### Tableau steps
- Put `batting_team` on **Detail**.
- Put `SUM(runs_off_bat)` on **Size** and **Color**.
- Use Circle marks.
- Add labels/tooltips.

In [13]:
print("Bubble chart metric summary:")
display(treemap_data)

Bubble chart metric summary:

                   batting_team  total_runs
0                Mumbai Indians       37523
1   Royal Challengers Bangalore       35810
2         Kolkata Knight Riders       34668
3           Chennai Super Kings       34334
4              Rajasthan Royals       30541
5               Kings XI Punjab       28541
6           Sunrisers Hyderabad       24735
7              Delhi Daredevils       23022
8                Delhi Capitals       11764
9               Deccan Chargers       10885
10                 Punjab Kings        6670
11                Pune Warriors        6040
12               Gujarat Titans        5423
13         Lucknow Super Giants        4731
14                Gujarat Lions        4629
15       Rising Pune Supergiant        2370
16      Rising Pune Supergiants        1962
17         Kochi Tuskers Kerala        1758

## Algorithm 10 – Filters and Parameters
Create filters for:
- `season`
- `batting_team`
- `bowling_team`
- `batter`
- `bowler`

Create a parameter named **Top N Teams** with Integer data type and current value 10. Use it in a ranking calculated field to control the number of teams displayed.

## Algorithm 11 – Calculated Fields
Create this Tableau calculated field:

**Runs Per Match**
```text
SUM([runs_off_bat]) / COUNTD([match_id])
```

This can be used in KPI cards, tooltips, tables, and dashboards.

In [14]:
total_runs = int(df["runs_off_bat"].sum())
total_matches = int(df["match_id"].nunique())
runs_per_match = round(total_runs / total_matches, 2)

print("Total batsman runs:", total_runs)
print("Total matches:", total_matches)
print("Runs per match:", runs_per_match)

Total batsman runs: 305406
Total matches: 1024
Runs per match: 298.25

## Algorithm 12 – Dashboard Creation
Create a dashboard named **IPL Performance Dashboard**.

Recommended components:
1. KPI cards – Total Runs, Total Matches, Runs Per Match
2. Season Runs – Line Chart
3. Team Runs – Bar Chart
4. Team Run Share – Pie Chart
5. Season × Team Heatmap
6. Team Treemap
7. Filters for Season, Batting Team, and Bowling Team

Use dashboard actions so selections update related visualizations.

In [15]:
kpis = pd.Series({
    "Total Runs": int(df["runs_off_bat"].sum()),
    "Total Matches": int(df["match_id"].nunique()),
    "Total Deliveries": int(len(df)),
    "Runs Per Match": round(df["runs_off_bat"].sum() / df["match_id"].nunique(), 2)
})
print("IPL Dashboard KPI values:")
display(kpis.to_frame("Value"))

IPL Dashboard KPI values:

                      Value
Total Runs        305406.00
Total Matches       1024.00
Total Deliveries  243815.00
Runs Per Match       298.25

## Algorithm 13 – Tableau Story
Create a Story named **IPL Data Visualization Story**.

Suggested story points:
1. IPL Overview
2. Season Trend
3. Team Comparison
4. Team Contribution
5. Season vs Team Heatmap
6. Interactive Analysis using filters and dashboard actions

## Applications
- Sports performance analysis
- Team comparison and ranking
- Player and batting analysis
- Season-wise performance tracking
- Interactive sports dashboards
- Data-driven decision making

## Advantages
- Interactive visualizations
- Multiple data-source support
- Filters and parameters
- Dashboards and stories
- Calculated fields and analytics
- Clear presentation of complex data

## Precautions
- Verify data types and aggregations.
- Use suitable chart types.
- Avoid unnecessary visual clutter.
- Use meaningful titles and labels.
- Check filters before interpreting results.
- Verify calculated fields.

## Result
The IPL ball-by-ball dataset was successfully prepared and analyzed for Tableau visualization. The experiment covers data connection, preparation, bar charts, line charts, pie charts, tables/cross-tabs, filters, parameters, calculated fields, heatmaps, treemaps, bubble charts, dashboards, and stories.

The numerical outputs in this notebook were generated from the actual IPL dataset. Tableau Desktop is required to create and save the final interactive `.twb` or `.twbx` workbook.